import { writeFileSync, mkdirSync } from 'node:fs'
import pg from 'pg'
import type { WaveletConfig, SqlFragment, QueryDef, ColumnType } from '@risingwave/wavelet'

const { Client } = pg

export async function generateClient(config: WaveletConfig): Promise<void> {
  // Event types are always known from config
  const eventTypes: TypedEntity[] = []
  const events = config.events ?? config.streams ?? {}
  for (const [eventName, eventDef] of Object.entries(events)) {
    const columns = Object.entries(eventDef.columns).map(([name, type]) => ({
      name,
      tsType: columnTypeToTs(type),
    }))
    eventTypes.push({ name: eventName, columns })
  }

  // Query types: try config-declared columns first, then RisingWave introspection, then generic
  const queryTypes: TypedEntity[] = []
  let dbClient: InstanceType<typeof Client> | null = null
  const queries = config.queries ?? config.views ?? {}

  for (const [queryName, queryDef] of Object.entries(queries)) {
    // Tier 1: explicit columns in config
    const declaredColumns = getQueryColumns(queryDef)
    if (declaredColumns) {
      queryTypes.push({ name: queryName, columns: declaredColumns })
      continue
    }

    // Tier 2: introspect from RisingWave (if reachable)
    if (!dbClient) {
      dbClient = await tryConnect(config.database)
    }

    if (dbClient) {
      try {
        const result = await dbClient.query(
          `SELECT column_name, data_type FROM information_schema.columns WHERE table_name = $1 ORDER BY ordinal_position`,
          [queryName]
        )
        if (result.rows.length > 0) {
          queryTypes.push({
            name: queryName,
            columns: result.rows.map((row: any) => ({
              name: row.column_name,
              tsType: pgTypeToTs(row.data_type),
            })),
          })
          continue
        }
      } catch {
        // Fall through to tier 3
      }
    }

    // Tier 3: generic fallback
    queryTypes.push({ name: queryName, columns: [] })
  }

  if (dbClient) {
    await dbClient.end().catch(() => {})
  }

  const code = generateCode(queryTypes, eventTypes)

  mkdirSync('.wavelet', { recursive: true })
  writeFileSync('.wavelet/client.ts', code)
}

interface TypedEntity {
  name: string
  columns: { name: string; tsType: string }[]
}

function getQueryColumns(queryDef: QueryDef | SqlFragment): { name: string; tsType: string }[] | null {
  // SqlFragment has no columns
  if ('_tag' in queryDef && queryDef._tag === 'sql') return null

  // QueryDef might have explicit columns
  const qd = queryDef as QueryDef
  if (!qd.columns) return null

  return Object.entries(qd.columns).map(([name, type]) => ({
    name,
    tsType: columnTypeToTs(type),
  }))
}

async function tryConnect(connectionString: string): Promise<InstanceType<typeof Client> | null> {
  const client = new Client({ connectionString, connectionTimeoutMillis: 3000 })
  try {
    await client.connect()
    return client
  } catch {
    return null
  }
}

function generateCode(queries: TypedEntity[], events: TypedEntity[]): string {
  let code = `// Auto-generated by wavelet generate - do not edit\n`
  code += `// Run 'npx wavelet generate' to regenerate\n\n`
  code += `import { WaveletClient } from '@risingwave/wavelet-sdk'\n`
  code += `import type { QueryHandle, EventHandle, Diff, WaveletClientOptions } from '@risingwave/wavelet-sdk'\n\n`

  // Query row types
  for (const q of queries) {
    const typeName = pascalCase(q.name) + 'Row'
    if (q.columns.length > 0) {
      code += `export interface ${typeName} {\n`
      for (const col of q.columns) {
        code += `  ${col.name}: ${col.tsType}\n`
      }
      code += `}\n\n`
    } else {
      code += `export type ${typeName} = Record<string, unknown>\n\n`
    }
  }

  // Event types
  for (const ev of events) {
    const typeName = pascalCase(ev.name) + 'Event'
    code += `export interface ${typeName} {\n`
    for (const col of ev.columns) {
      code += `  ${col.name}: ${col.tsType}\n`
    }
    code += `}\n\n`
  }

  // Typed client class
  code += `export class TypedWaveletClient {\n`
  code += `  private client: WaveletClient\n\n`
  code += `  constructor(options: WaveletClientOptions) {\n`
  code += `    this.client = new WaveletClient(options)\n`
  code += `  }\n\n`

  // Query accessors
  code += `  queries = {\n`
  for (const q of queries) {
    const typeName = pascalCase(q.name) + 'Row'
    code += `    ${q.name}: this.client.query<${typeName}>('${q.name}'),\n`
  }
  code += `  }\n\n`

  // Event accessors
  code += `  events = {\n`
  for (const ev of events) {
    const typeName = pascalCase(ev.name) + 'Event'
    code += `    ${ev.name}: this.client.event<${typeName}>('${ev.name}'),\n`
  }
  code += `  }\n`
  code += `}\n\n`

  // Query name literal type
  const queryNames = queries.map(q => `'${q.name}'`).join(' | ')
  code += `export type QueryName = ${queryNames || 'never'}\n\n`

  // React hook overloads
  code += `// React hook overloads for type-safe useWavelet\n`
  code += `import type { UseWaveletResult } from '@risingwave/wavelet-sdk/react'\n\n`
  for (const q of queries) {
    const typeName = pascalCase(q.name) + 'Row'
    code += `export declare function useWavelet(query: '${q.name}'): UseWaveletResult<${typeName}>\n`
  }

  return code
}

function pgTypeToTs(pgType: string): string {
  switch (pgType.toLowerCase()) {
    case 'integer':
    case 'bigint':
    case 'smallint':
    case 'real':
    case 'double precision':
    case 'numeric':
    case 'float':
    case 'int':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'jsonb':
    case 'json':
      return 'unknown'
    case 'timestamp with time zone':
    case 'timestamp without time zone':
    case 'timestamptz':
      return 'string'
    default:
      return 'string'
  }
}

function columnTypeToTs(colType: string): string {
  switch (colType) {
    case 'int':
    case 'float':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'json':
      return 'unknown'
    default:
      return 'string'
  }
}

function pascalCase(str: string): string {
  return str
    .split(/[_\s-]+/)
    .map(s => s.charAt(0).toUpperCase() + s.slice(1))
    .join('')
}
