import { writeFileSync, mkdirSync } from 'node:fs'
import pg from 'pg'
import type { WaveletConfig, SqlFragment, ViewDef } from 'wavelet'

const { Client } = pg

export async function generateClient(config: WaveletConfig): Promise<void> {
  const client = new Client({ connectionString: config.database })
  await client.connect()

  const viewTypes: { name: string; columns: { name: string; tsType: string }[] }[] = []

  for (const viewName of Object.keys(config.views ?? {})) {
    try {
      // Query column info from RisingWave
      const result = await client.query(
        `SELECT column_name, data_type FROM information_schema.columns WHERE table_name = $1 ORDER BY ordinal_position`,
        [viewName]
      )

      const columns = result.rows.map((row: any) => ({
        name: row.column_name,
        tsType: pgTypeToTs(row.data_type),
      }))

      viewTypes.push({ name: viewName, columns })
    } catch {
      // If we can't query schema, generate generic types
      viewTypes.push({ name: viewName, columns: [] })
    }
  }

  const streamTypes: { name: string; columns: { name: string; tsType: string }[] }[] = []

  for (const [streamName, streamDef] of Object.entries(config.streams ?? {})) {
    const columns = Object.entries(streamDef.columns).map(([name, type]) => ({
      name,
      tsType: columnTypeToTs(type),
    }))
    streamTypes.push({ name: streamName, columns })
  }

  await client.end()

  const code = generateCode(viewTypes, streamTypes)

  mkdirSync('.wavelet', { recursive: true })
  writeFileSync('.wavelet/client.ts', code)
}

function generateCode(
  views: { name: string; columns: { name: string; tsType: string }[] }[],
  streams: { name: string; columns: { name: string; tsType: string }[] }[]
): string {
  let code = `// Auto-generated by wavelet generate - do not edit\n`
  code += `// Run 'npx wavelet generate' to regenerate\n\n`
  code += `import { WaveletClient } from '@wavelet/sdk'\n`
  code += `import type { ViewHandle, StreamHandle, Diff, WaveletClientOptions } from '@wavelet/sdk'\n\n`

  // View row types
  for (const view of views) {
    const typeName = pascalCase(view.name) + 'Row'
    if (view.columns.length > 0) {
      code += `export interface ${typeName} {\n`
      for (const col of view.columns) {
        code += `  ${col.name}: ${col.tsType}\n`
      }
      code += `}\n\n`
    } else {
      code += `export type ${typeName} = Record<string, unknown>\n\n`
    }
  }

  // Stream event types
  for (const stream of streams) {
    const typeName = pascalCase(stream.name) + 'Event'
    code += `export interface ${typeName} {\n`
    for (const col of stream.columns) {
      code += `  ${col.name}: ${col.tsType}\n`
    }
    code += `}\n\n`
  }

  // Typed client class
  code += `export class TypedWaveletClient {\n`
  code += `  private client: WaveletClient\n\n`
  code += `  constructor(options: WaveletClientOptions) {\n`
  code += `    this.client = new WaveletClient(options)\n`
  code += `  }\n\n`

  // View accessors
  code += `  views = {\n`
  for (const view of views) {
    const typeName = pascalCase(view.name) + 'Row'
    code += `    ${view.name}: this.client.view<${typeName}>('${view.name}'),\n`
  }
  code += `  }\n\n`

  // Stream accessors
  code += `  streams = {\n`
  for (const stream of streams) {
    const typeName = pascalCase(stream.name) + 'Event'
    code += `    ${stream.name}: this.client.stream<${typeName}>('${stream.name}'),\n`
  }
  code += `  }\n`
  code += `}\n\n`

  // View name literal type
  const viewNames = views.map(v => `'${v.name}'`).join(' | ')
  code += `export type ViewName = ${viewNames || 'never'}\n\n`

  // React hook overloads
  code += `// React hook overloads for type-safe useWavelet\n`
  code += `import type { UseWaveletResult } from '@wavelet/sdk/react'\n\n`
  for (const view of views) {
    const typeName = pascalCase(view.name) + 'Row'
    code += `export declare function useWavelet(view: '${view.name}'): UseWaveletResult<${typeName}>\n`
  }

  return code
}

function pgTypeToTs(pgType: string): string {
  switch (pgType.toLowerCase()) {
    case 'integer':
    case 'bigint':
    case 'smallint':
    case 'real':
    case 'double precision':
    case 'numeric':
    case 'float':
    case 'int':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'jsonb':
    case 'json':
      return 'unknown'
    case 'timestamp with time zone':
    case 'timestamp without time zone':
    case 'timestamptz':
      return 'string'
    default:
      return 'string'
  }
}

function columnTypeToTs(colType: string): string {
  switch (colType) {
    case 'int':
    case 'float':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'json':
      return 'unknown'
    default:
      return 'string'
  }
}

function pascalCase(str: string): string {
  return str
    .split(/[_\s-]+/)
    .map(s => s.charAt(0).toUpperCase() + s.slice(1))
    .join('')
}
