import { writeFileSync, mkdirSync } from 'node:fs'
import pg from 'pg'
import type { WaveletConfig, SqlFragment, ViewDef, ColumnType } from '@risingwave/wavelet'

const { Client } = pg

export async function generateClient(config: WaveletConfig): Promise<void> {
  // Stream types are always known from config
  const streamTypes: TypedEntity[] = []
  for (const [streamName, streamDef] of Object.entries(config.streams ?? {})) {
    const columns = Object.entries(streamDef.columns).map(([name, type]) => ({
      name,
      tsType: columnTypeToTs(type),
    }))
    streamTypes.push({ name: streamName, columns })
  }

  // View types: try config-declared columns first, then RisingWave introspection, then generic
  const viewTypes: TypedEntity[] = []
  let dbClient: InstanceType<typeof Client> | null = null

  for (const [viewName, viewDef] of Object.entries(config.views ?? {})) {
    // Tier 1: explicit columns in config
    const declaredColumns = getViewColumns(viewDef)
    if (declaredColumns) {
      viewTypes.push({ name: viewName, columns: declaredColumns })
      continue
    }

    // Tier 2: introspect from RisingWave (if reachable)
    if (!dbClient) {
      dbClient = await tryConnect(config.database)
    }

    if (dbClient) {
      try {
        const result = await dbClient.query(
          `SELECT column_name, data_type FROM information_schema.columns WHERE table_name = $1 ORDER BY ordinal_position`,
          [viewName]
        )
        if (result.rows.length > 0) {
          viewTypes.push({
            name: viewName,
            columns: result.rows.map((row: any) => ({
              name: row.column_name,
              tsType: pgTypeToTs(row.data_type),
            })),
          })
          continue
        }
      } catch {
        // Fall through to tier 3
      }
    }

    // Tier 3: generic fallback
    viewTypes.push({ name: viewName, columns: [] })
  }

  if (dbClient) {
    await dbClient.end().catch(() => {})
  }

  const code = generateCode(viewTypes, streamTypes)

  mkdirSync('.wavelet', { recursive: true })
  writeFileSync('.wavelet/client.ts', code)
}

interface TypedEntity {
  name: string
  columns: { name: string; tsType: string }[]
}

function getViewColumns(viewDef: ViewDef | SqlFragment): { name: string; tsType: string }[] | null {
  // SqlFragment has no columns
  if ('_tag' in viewDef && viewDef._tag === 'sql') return null

  // ViewDef might have explicit columns
  const vd = viewDef as ViewDef
  if (!vd.columns) return null

  return Object.entries(vd.columns).map(([name, type]) => ({
    name,
    tsType: columnTypeToTs(type),
  }))
}

async function tryConnect(connectionString: string): Promise<InstanceType<typeof Client> | null> {
  const client = new Client({ connectionString, connectionTimeoutMillis: 3000 })
  try {
    await client.connect()
    return client
  } catch {
    return null
  }
}

function generateCode(views: TypedEntity[], streams: TypedEntity[]): string {
  let code = `// Auto-generated by wavelet generate - do not edit\n`
  code += `// Run 'npx wavelet generate' to regenerate\n\n`
  code += `import { WaveletClient } from '@risingwave/wavelet-sdk'\n`
  code += `import type { ViewHandle, StreamHandle, Diff, WaveletClientOptions } from '@risingwave/wavelet-sdk'\n\n`

  // View row types
  for (const view of views) {
    const typeName = pascalCase(view.name) + 'Row'
    if (view.columns.length > 0) {
      code += `export interface ${typeName} {\n`
      for (const col of view.columns) {
        code += `  ${col.name}: ${col.tsType}\n`
      }
      code += `}\n\n`
    } else {
      code += `export type ${typeName} = Record<string, unknown>\n\n`
    }
  }

  // Stream event types
  for (const stream of streams) {
    const typeName = pascalCase(stream.name) + 'Event'
    code += `export interface ${typeName} {\n`
    for (const col of stream.columns) {
      code += `  ${col.name}: ${col.tsType}\n`
    }
    code += `}\n\n`
  }

  // Typed client class
  code += `export class TypedWaveletClient {\n`
  code += `  private client: WaveletClient\n\n`
  code += `  constructor(options: WaveletClientOptions) {\n`
  code += `    this.client = new WaveletClient(options)\n`
  code += `  }\n\n`

  // View accessors
  code += `  views = {\n`
  for (const view of views) {
    const typeName = pascalCase(view.name) + 'Row'
    code += `    ${view.name}: this.client.view<${typeName}>('${view.name}'),\n`
  }
  code += `  }\n\n`

  // Stream accessors
  code += `  streams = {\n`
  for (const stream of streams) {
    const typeName = pascalCase(stream.name) + 'Event'
    code += `    ${stream.name}: this.client.stream<${typeName}>('${stream.name}'),\n`
  }
  code += `  }\n`
  code += `}\n\n`

  // View name literal type
  const viewNames = views.map(v => `'${v.name}'`).join(' | ')
  code += `export type ViewName = ${viewNames || 'never'}\n\n`

  // React hook overloads
  code += `// React hook overloads for type-safe useWavelet\n`
  code += `import type { UseWaveletResult } from '@risingwave/wavelet-sdk/react'\n\n`
  for (const view of views) {
    const typeName = pascalCase(view.name) + 'Row'
    code += `export declare function useWavelet(view: '${view.name}'): UseWaveletResult<${typeName}>\n`
  }

  return code
}

function pgTypeToTs(pgType: string): string {
  switch (pgType.toLowerCase()) {
    case 'integer':
    case 'bigint':
    case 'smallint':
    case 'real':
    case 'double precision':
    case 'numeric':
    case 'float':
    case 'int':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'jsonb':
    case 'json':
      return 'unknown'
    case 'timestamp with time zone':
    case 'timestamp without time zone':
    case 'timestamptz':
      return 'string'
    default:
      return 'string'
  }
}

function columnTypeToTs(colType: string): string {
  switch (colType) {
    case 'int':
    case 'float':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'json':
      return 'unknown'
    default:
      return 'string'
  }
}

function pascalCase(str: string): string {
  return str
    .split(/[_\s-]+/)
    .map(s => s.charAt(0).toUpperCase() + s.slice(1))
    .join('')
}
